### ISSUE TITLE
tasks get_upcoming_events_date | TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by r00t9** [guanquann/Stocksera#25]
I am running like this 
`sudo docker run --rm stocksera_scheduled_tasks python3  scheduled_tasks/economy/get_upcoming_events_date.py`
and get this error ? do you have also the same issue
```
Traceback (most recent call last):
  File "scheduled_tasks/economy/get_upcoming_events_date.py", line 99, in <module>
    main()
  File "scheduled_tasks/economy/get_upcoming_events_date.py", line 82, in main
    rrp_treasury_date = get_next_rrp_treasury_date(datetime.strptime(record_date[0], "%Y-%m-%d") + timedelta(days=1))
TypeError: 'NoneType' object is not subscriptable

```

**Comment by guanquann** [comment]
No issues for me. It seems like you need to run scheduled_tasks/economy/get_reverse_repo.py first.

**Comment by r00t9** [comment]
thanks :D :)
