### ISSUE TITLE
TypeError: unhashable type: 'slice'

### ISSUE THREAD

**Issue by Mgelius** [guanquann/Stocksera#29]
python3 manage.py runserver 0.0.0.0:8000
Watching for file changes with StatReloader
Performing system checks...

SQL SERVER IS CONNECTED...
Version 7.2.0 of praw is outdated. Version 7.5.0 was released Sunday November 14, 2021.
SQL SERVER IS CONNECTED...
Not authorised to have access to admin functions
SQL SERVER IS CONNECTED...
System check identified no issues (0 silenced).
May 04, 2022 - 20:38:15
Django version 3.1.6, using settings 'stocksera.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[04/May/2022 20:38:29] "GET /api/stocksera_trending HTTP/1.1" 301 0
[04/May/2022 20:38:29] "GET /api/stocksera_trending/ HTTP/1.1" 200 60
Internal Server Error: /
Traceback (most recent call last):
  File "/home/settd/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/settd/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/settd/stocks/Stocksera/app/views.py", line 34, in main
    data = requests.get(f"{BASE_URL}/stocksera_trending", headers=HEADERS).json()[:10]
TypeError: unhashable type: 'slice'
[04/May/2022 20:38:29] "GET / HTTP/1.1" 500 61768

Sorry that may be a novice question, but any help would be much appreciated!

**Comment by guanquann** [comment]
This problem should be fixed with the latest commit! Sorry for the late reply 😅.
