### ISSUE TITLE
Unexpected error on Short Vol

### ISSUE THREAD

**Issue by CodeInFilth** [guanquann/Stocksera#44]
So i was running this yesteraday and got rid of all the errors except previously specified ones in issues.

now I am seeing this issue ? I am sorry haha

It is on the short vol request after grabbing the vol .txt's

```
dn.finra.org/equity/regsho/daily/CNMSshvol20230525.txt
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/multitasking/__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "/code/scheduled_tasks/reddit/stocks/fast_yahoo.py", line 184, in quick_stats_request_threaded
    shared.response_dict[request_idx] = quick_stats_request(request_symbol_list, field_list)
  File "/code/scheduled_tasks/reddit/stocks/fast_yahoo.py", line 194, in quick_stats_request
    'symbols': ','.join(request_symbol_list),
TypeError: sequence item 45: expected str instance, float found
```

**Comment by guanquann** [comment]
Its because fast_yahoo.py is not working haha :/
You can uncomment out that line for the time being D:

**Comment by guanquann** [comment]
I have fixed the fast_yahoo issue. Please use the latest commit version.
